server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/learn?characterEncoding=utf8
    password: lfc119233
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
    level:
      root: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
